from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_NewOrder(object):
    draw = 0
    k = 0.1
    sizes = [0, 0, 0, 0, 0, 0, 0]
    divide = [0, 0, 0, 0, 0, 0, 0]
    materials = ['', '', '', '', '', '', '']

    def add_connect(self):
        self.size_1.clicked.connect(lambda: self.show_set_size(0))
        self.size_2.clicked.connect(lambda: self.show_set_size(1))
        self.size_3.clicked.connect(lambda: self.show_set_size(2))
        self.size_4.clicked.connect(lambda: self.show_set_size(3))
        self.size5.clicked.connect(lambda: self.show_set_size(4))
        self.size_6.clicked.connect(lambda: self.show_set_size(5))
        self.size_7.clicked.connect(lambda: self.show_set_size(6))

        self.btn_merge.clicked.connect(lambda: self.draw.merge())
        self.btn_up_draw.clicked.connect(self.update)

        self.btn_plus.clicked.connect(lambda: self.scale(0))
        self.btn_nimus.clicked.connect(lambda: self.scale(1))
        self.btn_grass.clicked.connect(lambda: self.draw_material('Стекло'))
        self.btn_mirror.clicked.connect(lambda: self.draw_material('Зеркало'))
        self.btn_LDSP.clicked.connect(lambda: self.draw_material('ЛДСП'))
        self.btn_unmerge.clicked.connect(lambda: self.draw.unmerge())

    @staticmethod
    def norm_value(value, default=1):
        if value == '' or not value.isdigit():
            return default
        else:
            return int(value)

    def scale(self, action):
        if action == 0:
            self.k += 0.05
        else:
            self.k -= 0.05
        self.draw.update_scale(self.k)

    def draw_material(self, material):
        self.draw.change_materials(material)

    def normalize_all_value(self):
        self.doors = self.norm_value(self.inp_door.text())
        self.height = self.norm_value(self.inp_height.text())
        self.long = self.norm_value(self.inp_long.text())

        for i in range(self.doors):
            l, h = self.norm_value(eval(f"self.l{i+1}.text()")), self.norm_value(eval(f"self.h{i+1}.text()"))
            self.divide[i] = (h, l)
            if self.sizes[i] == 0 or len(self.sizes[i]) != h and len(self.sizes[i][0]) != l:
                self.sizes[i] = [ [0 for _ in range(h)], [0 for _ in range(l)] ]
            self.materials[i] = eval(f"self.mat{i+1}.currentText()")


    def show_set_size(self, n):
        from set_size_window import SetSizeDialog
        self.normalize_all_value()
        h, l = self.divide[n]
        if h > 15 or l > 15:
            QMessageBox.warning(NewOrder, "Ошибка", "Слишком большое значение.")
            return
        set_size_dialog = SetSizeDialog(self.sizes[n], h, l)
        size = set_size_dialog.size
        if type(size) == list:
            if 0 not in size[0] or 0 not in size[1] or sum(size[0]) >= self.long or sum(size[1]) >= self.height // self.doors:
                QMessageBox.warning(NewOrder, "Ошибка", "Недопустимые значения.")
            else:
                self.sizes[n] = size

    def update(self):
        from grawing import Drawing
        self.normalize_all_value()
        if self.draw != 0:
            self.verticalGroupBox.layout().removeWidget(self.draw)
        self.draw = Drawing(self.centralwidget, self.height, self.long, self.doors, self.divide, self.sizes, self.k, self.materials)
        self.verticalGroupBox.layout().addWidget(self.draw)

    def setupUi(self, NewOrder):
        NewOrder.resize(1000, 800)

        self.centralwidget = QtWidgets.QWidget(NewOrder)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.config_zone = QtWidgets.QVBoxLayout()
        self.UpButtons = QtWidgets.QHBoxLayout()
        self.btn_update = QtWidgets.QPushButton(self.centralwidget)
        self.UpButtons.addWidget(self.btn_update)
        self.btn_zero = QtWidgets.QPushButton(self.centralwidget)
        self.UpButtons.addWidget(self.btn_zero)
        self.btn_quit = QtWidgets.QPushButton(self.centralwidget)
        self.UpButtons.addWidget(self.btn_quit)
        self.btn_frofiles = QtWidgets.QPushButton(self.centralwidget)
        self.btn_frofiles.clicked.connect(self.normalize_all_value)
        self.UpButtons.addWidget(self.btn_frofiles)
        self.btn_up_draw = QtWidgets.QPushButton(self.centralwidget)

        self.UpButtons.addWidget(self.btn_up_draw)
        self.config_zone.addLayout(self.UpButtons)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 500, 1244))
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.ch_needsealer = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.addWidget(self.ch_needsealer)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_2.addWidget(self.label_5)
        self.size_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.size_1.setMaximumSize(QtCore.QSize(28, 28))
        self.horizontalLayout_2.addWidget(self.size_1)
        self.mat1 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mat1.sizePolicy().hasHeightForWidth())
        self.mat1.setSizePolicy(sizePolicy)
        self.mat1.addItem("")
        self.mat1.addItem("")
        self.mat1.addItem("")
        self.horizontalLayout_2.addWidget(self.mat1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.h1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.h1)
        self.l1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.l1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.addWidget(self.label_6)
        self.size_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.size_2.setMaximumSize(QtCore.QSize(28, 28))
        self.horizontalLayout_3.addWidget(self.size_2)
        self.mat2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mat2.sizePolicy().hasHeightForWidth())
        self.mat2.setSizePolicy(sizePolicy)
        self.mat2.addItem("")
        self.mat2.addItem("")
        self.mat2.addItem("")
        self.horizontalLayout_3.addWidget(self.mat2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.h2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.h2)
        self.l2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.l2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_4.addWidget(self.label_7)
        self.size_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.size_3.setMaximumSize(QtCore.QSize(28, 28))
        self.horizontalLayout_4.addWidget(self.size_3)
        self.mat3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mat3.sizePolicy().hasHeightForWidth())
        self.mat3.setSizePolicy(sizePolicy)
        self.mat3.addItem("")
        self.mat3.addItem("")
        self.mat3.addItem("")
        self.horizontalLayout_4.addWidget(self.mat3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.h3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.h3)
        self.l3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.l3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_5.addWidget(self.label_8)
        self.size_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.size_4.setMaximumSize(QtCore.QSize(28, 28))
        self.horizontalLayout_5.addWidget(self.size_4)
        self.mat4 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mat4.sizePolicy().hasHeightForWidth())
        self.mat4.setSizePolicy(sizePolicy)
        self.mat4.addItem("")
        self.mat4.addItem("")
        self.mat4.addItem("")
        self.horizontalLayout_5.addWidget(self.mat4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.h4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.h4)
        self.l4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.l4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_6.addWidget(self.label_9)
        self.size5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.size5.setMaximumSize(QtCore.QSize(28, 28))
        self.horizontalLayout_6.addWidget(self.size5)
        self.mat5 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mat5.sizePolicy().hasHeightForWidth())
        self.mat5.setSizePolicy(sizePolicy)
        self.mat5.addItem("")
        self.mat5.addItem("")
        self.mat5.addItem("")
        self.horizontalLayout_6.addWidget(self.mat5)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.h5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.h5)
        self.l5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.addWidget(self.l5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_7.addWidget(self.label_10)
        self.size_6 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.size_6.setMaximumSize(QtCore.QSize(28, 28))
        self.horizontalLayout_7.addWidget(self.size_6)
        self.mat6 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mat6.sizePolicy().hasHeightForWidth())
        self.mat6.setSizePolicy(sizePolicy)
        self.mat6.addItem("")
        self.mat6.addItem("")
        self.mat6.addItem("")
        self.horizontalLayout_7.addWidget(self.mat6)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.h6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.h6)
        self.l6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.l6)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_8.addWidget(self.label_11)
        self.size_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.size_7.setMaximumSize(QtCore.QSize(28, 28))
        self.horizontalLayout_8.addWidget(self.size_7)
        self.mat7 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mat7.sizePolicy().hasHeightForWidth())
        self.mat7.setSizePolicy(sizePolicy)
        self.mat7.addItem("")
        self.mat7.addItem("")
        self.mat7.addItem("")
        self.horizontalLayout_8.addWidget(self.mat7)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.h7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.addWidget(self.h7)
        self.l7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.verticalLayout_7.addWidget(self.l7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.gridLayout.addLayout(self.verticalLayout_8, 1, 0, 3, 1)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(2)
        self.groupBox_10 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setTitle("")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_10)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setHorizontalSpacing(0)
        self.formLayout_6.setVerticalSpacing(3)
        self.glass_w = QtWidgets.QLabel(self.groupBox_10)
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.glass_w)
        self.inp_glass_w = QtWidgets.QLineEdit(self.groupBox_10)
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inp_glass_w)
        self.mirror_w = QtWidgets.QLabel(self.groupBox_10)
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mirror_w)
        self.inp_mirror_w = QtWidgets.QLineEdit(self.groupBox_10)
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inp_mirror_w)
        self.LDSP_w = QtWidgets.QLabel(self.groupBox_10)
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.LDSP_w)
        self.inp_LDSP_w = QtWidgets.QLineEdit(self.groupBox_10)
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inp_LDSP_w)
        self.verticalLayout_18.addWidget(self.groupBox_10)
        self.groupBox_13 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_13.sizePolicy().hasHeightForWidth())
        self.groupBox_13.setSizePolicy(sizePolicy)
        self.groupBox_13.setTitle("")
        self.formLayout_9 = QtWidgets.QFormLayout(self.groupBox_13)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setSpacing(0)
        self.overlay_long = QtWidgets.QLabel(self.groupBox_13)
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.overlay_long)
        self.inp_overlay_long = QtWidgets.QLineEdit(self.groupBox_13)
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inp_overlay_long)
        self.inp_overlay_count = QtWidgets.QLineEdit(self.groupBox_13)
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.inp_overlay_count)
        self.overlay_count = QtWidgets.QLabel(self.groupBox_13)
        self.formLayout_9.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.overlay_count)
        self.r_no_overlay = QtWidgets.QRadioButton(self.groupBox_13)
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.r_no_overlay)
        self.r_have_overlay = QtWidgets.QRadioButton(self.groupBox_13)
        self.r_have_overlay.setChecked(True)
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.r_have_overlay)
        self.verticalLayout_18.addWidget(self.groupBox_13)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setTitle("")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.r_have_schlegel = QtWidgets.QRadioButton(self.groupBox_2)
        self.r_have_schlegel.setChecked(True)
        self.verticalLayout_9.addWidget(self.r_have_schlegel)
        self.r_no_schlegel = QtWidgets.QRadioButton(self.groupBox_2)
        self.verticalLayout_9.addWidget(self.r_no_schlegel)
        self.verticalLayout_18.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_3.setTitle("")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.r_2_guide = QtWidgets.QRadioButton(self.groupBox_3)
        self.r_2_guide.setChecked(True)
        self.verticalLayout_10.addWidget(self.r_2_guide)
        self.r_1_guide = QtWidgets.QRadioButton(self.groupBox_3)
        self.verticalLayout_10.addWidget(self.r_1_guide)
        self.verticalLayout_18.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_4.setTitle("")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.r_black_char = QtWidgets.QRadioButton(self.groupBox_4)
        self.r_black_char.setChecked(True)
        self.verticalLayout_11.addWidget(self.r_black_char)
        self.r_white_char = QtWidgets.QRadioButton(self.groupBox_4)
        self.verticalLayout_11.addWidget(self.r_white_char)
        self.verticalLayout_18.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_5.setTitle("")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.r_no_fraction = QtWidgets.QRadioButton(self.groupBox_5)
        self.r_no_fraction.setChecked(True)
        self.verticalLayout_12.addWidget(self.r_no_fraction)
        self.r_show_fraction = QtWidgets.QRadioButton(self.groupBox_5)
        self.verticalLayout_12.addWidget(self.r_show_fraction)
        self.verticalLayout_18.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_6.setTitle("")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.r_no_pack = QtWidgets.QRadioButton(self.groupBox_6)
        self.r_no_pack.setChecked(True)
        self.verticalLayout_13.addWidget(self.r_no_pack)
        self.r_packin_tape = QtWidgets.QRadioButton(self.groupBox_6)
        self.verticalLayout_13.addWidget(self.r_packin_tape)
        self.r_packin_corrugation = QtWidgets.QRadioButton(self.groupBox_6)
        self.verticalLayout_13.addWidget(self.r_packin_corrugation)
        self.r_packin_box = QtWidgets.QRadioButton(self.groupBox_6)
        self.verticalLayout_13.addWidget(self.r_packin_box)
        self.verticalLayout_18.addWidget(self.groupBox_6)
        self.groupBox_8 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_8.setTitle("")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.r_mechanismR = QtWidgets.QRadioButton(self.groupBox_8)
        self.r_mechanismR.setChecked(True)
        self.verticalLayout_15.addWidget(self.r_mechanismR)
        self.r_mechanismUFK = QtWidgets.QRadioButton(self.groupBox_8)
        self.verticalLayout_15.addWidget(self.r_mechanismUFK)
        self.verticalLayout_18.addWidget(self.groupBox_8)
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_7.setTitle("")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.r_build = QtWidgets.QRadioButton(self.groupBox_7)
        self.r_build.setChecked(True)
        self.verticalLayout_14.addWidget(self.r_build)
        self.r_cut = QtWidgets.QRadioButton(self.groupBox_7)
        self.verticalLayout_14.addWidget(self.r_cut)
        self.r_cutandrill = QtWidgets.QRadioButton(self.groupBox_7)
        self.verticalLayout_14.addWidget(self.r_cutandrill)
        self.verticalLayout_18.addWidget(self.groupBox_7)
        self.gridLayout.addLayout(self.verticalLayout_18, 7, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.date = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.date)
        self.inp_date = QtWidgets.QDateEdit(self.scrollAreaWidgetContents_2)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inp_date)
        self.norder = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.norder)
        self.int_norder = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.int_norder)
        self.dateout = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.dateout)
        self.inp_date_uot = QtWidgets.QDateEdit(self.scrollAreaWidgetContents_2)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inp_date_uot)
        self.discription = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.discription)
        self.inp_discription = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.inp_discription)
        self.color = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.color)
        self.inp_color = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.inp_color)
        self.gridLayout.addLayout(self.formLayout_2, 0, 1, 2, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.profille = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.addWidget(self.profille, 3, 0, 1, 1)
        self.inp_profile = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.addWidget(self.inp_profile, 3, 1, 1, 1)
        self.customer = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.addWidget(self.customer, 0, 0, 1, 1)
        self.inp_customer = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.addWidget(self.inp_customer, 0, 1, 1, 1)
        self.list_customers = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_customers.sizePolicy().hasHeightForWidth())
        self.list_customers.setSizePolicy(sizePolicy)
        self.gridLayout_3.addWidget(self.list_customers, 1, 1, 1, 1)
        self.btn_add_to_db = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.addWidget(self.btn_add_to_db, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 2, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.door = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.door)
        self.inp_door = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.inp_door.setMinimum(1)
        self.inp_door.setMaximum(7)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inp_door)
        self.height = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.height)
        self.inp_height = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inp_height)
        self.long_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.long_2)
        self.inp_long = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inp_long)
        self.longL2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.longL2)
        self.inp_longL2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.inp_longL2)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.list_profile = QtWidgets.QListWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.list_profile, 3, 1, 1, 1)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.groupBox_14 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_14.sizePolicy().hasHeightForWidth())
        self.groupBox_14.setSizePolicy(sizePolicy)
        self.groupBox_14.setTitle("")
        self.formLayout_10 = QtWidgets.QFormLayout(self.groupBox_14)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setSpacing(0)
        self.r_nostandart_overlap = QtWidgets.QRadioButton(self.groupBox_14)
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.r_nostandart_overlap)
        self.r_no_overlap = QtWidgets.QRadioButton(self.groupBox_14)
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.r_no_overlap)
        self.inp_overlap_count = QtWidgets.QLabel(self.groupBox_14)
        self.formLayout_10.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.inp_overlap_count)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_14)
        self.formLayout_10.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.r_standart_overlap = QtWidgets.QRadioButton(self.groupBox_14)
        self.r_standart_overlap.setChecked(True)
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.r_standart_overlap)
        self.verticalLayout_20.addWidget(self.groupBox_14)
        self.groupBox_11 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox_11)
        self.formLayout_7.setContentsMargins(9, 9, 0, 9)
        self.formLayout_7.setHorizontalSpacing(9)
        self.formLayout_7.setVerticalSpacing(3)
        self.def_tape = QtWidgets.QLabel(self.groupBox_11)
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.def_tape)
        self.inp_deftape = QtWidgets.QLineEdit(self.groupBox_11)
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inp_deftape)
        self.stop_up = QtWidgets.QLabel(self.groupBox_11)
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.stop_up)
        self.inp_stop_up = QtWidgets.QLineEdit(self.groupBox_11)
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inp_stop_up)
        self.stop_down = QtWidgets.QLabel(self.groupBox_11)
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.stop_down)
        self.inp_stop_dowm = QtWidgets.QLineEdit(self.groupBox_11)
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inp_stop_dowm)
        self.posicioner = QtWidgets.QLabel(self.groupBox_11)
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.posicioner)
        self.inp_posicioner = QtWidgets.QLineEdit(self.groupBox_11)
        self.formLayout_7.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.inp_posicioner)
        self.plug = QtWidgets.QLabel(self.groupBox_11)
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.plug)
        self.inp_plug = QtWidgets.QLineEdit(self.groupBox_11)
        self.formLayout_7.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.inp_plug)
        self.pin_to_door = QtWidgets.QLabel(self.groupBox_11)
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pin_to_door)
        self.inp_pin_to_dooe = QtWidgets.QLineEdit(self.groupBox_11)
        self.formLayout_7.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.inp_pin_to_dooe)
        self.add_shlegel = QtWidgets.QLabel(self.groupBox_11)
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.add_shlegel)
        self.inp_add_shlegel = QtWidgets.QLineEdit(self.groupBox_11)
        self.formLayout_7.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.inp_add_shlegel)
        self.add_sealer = QtWidgets.QLabel(self.groupBox_11)
        self.formLayout_7.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.add_sealer)
        self.inp_add_sealer = QtWidgets.QLineEdit(self.groupBox_11)
        self.formLayout_7.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.inp_add_sealer)
        self.verticalLayout_20.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        self.formLayout_8 = QtWidgets.QFormLayout(self.groupBox_12)
        self.formLayout_8.setContentsMargins(9, 9, 0, 9)
        self.formLayout_8.setHorizontalSpacing(9)
        self.formLayout_8.setVerticalSpacing(3)
        self.vertical_hand = QtWidgets.QLabel(self.groupBox_12)
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.vertical_hand)
        self.inp_vertical_hand = QtWidgets.QLineEdit(self.groupBox_12)
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inp_vertical_hand)
        self.rolic_up = QtWidgets.QLabel(self.groupBox_12)
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.rolic_up)
        self.inp_rolic = QtWidgets.QLineEdit(self.groupBox_12)
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.inp_rolic)
        self.plug_under_hand = QtWidgets.QLabel(self.groupBox_12)
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.plug_under_hand)
        self.inp_plug_under_hand = QtWidgets.QLineEdit(self.groupBox_12)
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inp_plug_under_hand)
        self.hand_fasteners = QtWidgets.QLabel(self.groupBox_12)
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.hand_fasteners)
        self.inp_hand_fasteners = QtWidgets.QLineEdit(self.groupBox_12)
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.inp_hand_fasteners)
        self.def_tape_stok = QtWidgets.QLabel(self.groupBox_12)
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.def_tape_stok)
        self.inp_def_tape_stok = QtWidgets.QLineEdit(self.groupBox_12)
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.inp_def_tape_stok)
        self.door_loop = QtWidgets.QLabel(self.groupBox_12)
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.door_loop)
        self.inp_door_loop = QtWidgets.QLineEdit(self.groupBox_12)
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.inp_door_loop)
        self.loop_4 = QtWidgets.QLabel(self.groupBox_12)
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.loop_4)
        self.inp_loop_4 = QtWidgets.QLineEdit(self.groupBox_12)
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.inp_loop_4)
        self.plug_stok = QtWidgets.QLabel(self.groupBox_12)
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.plug_stok)
        self.inp_plug_stok = QtWidgets.QLineEdit(self.groupBox_12)
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.inp_plug_stok)
        self.pin_to_door_stok = QtWidgets.QLabel(self.groupBox_12)
        self.formLayout_8.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.pin_to_door_stok)
        self.inp_pin_to_door_stok = QtWidgets.QLineEdit(self.groupBox_12)
        self.formLayout_8.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.inp_pin_to_door_stok)
        self.verticalLayout_20.addWidget(self.groupBox_12)
        self.groupBox_9 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_9.setTitle("")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.r_no_dilivery = QtWidgets.QRadioButton(self.groupBox_9)
        self.r_no_dilivery.setChecked(True)
        self.verticalLayout_16.addWidget(self.r_no_dilivery)
        self.radioButton_3r_dilivery = QtWidgets.QRadioButton(self.groupBox_9)
        self.verticalLayout_16.addWidget(self.radioButton_3r_dilivery)
        self.verticalLayout_20.addWidget(self.groupBox_9)
        self.gridLayout.addLayout(self.verticalLayout_20, 7, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.config_zone.addWidget(self.scrollArea)
        self.horizontalLayout.addLayout(self.config_zone)
        self.drawind_zone = QtWidgets.QVBoxLayout()
        self.verticalGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalGroupBox.sizePolicy().hasHeightForWidth())
        self.verticalGroupBox.setSizePolicy(sizePolicy)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.drawind_zone.addWidget(self.verticalGroupBox)
        self.tools = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools.sizePolicy().hasHeightForWidth())
        self.tools.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tools)
        self.btn_nimus = QtWidgets.QPushButton(self.tools)
        self.gridLayout_2.addWidget(self.btn_nimus, 2, 1, 1, 1)
        self.btn_grass = QtWidgets.QPushButton(self.tools)
        self.gridLayout_2.addWidget(self.btn_grass, 0, 2, 1, 1)
        self.btn_mirror = QtWidgets.QPushButton(self.tools)
        self.gridLayout_2.addWidget(self.btn_mirror, 1, 2, 1, 1)
        self.btn_LDSP = QtWidgets.QPushButton(self.tools)
        self.gridLayout_2.addWidget(self.btn_LDSP, 2, 2, 1, 1)
        self.btn_plus = QtWidgets.QPushButton(self.tools)
        self.gridLayout_2.addWidget(self.btn_plus, 2, 0, 1, 1)
        self.btn_unmerge = QtWidgets.QPushButton(self.tools)
        self.gridLayout_2.addWidget(self.btn_unmerge, 1, 0, 1, 2)
        self.btn_merge = QtWidgets.QPushButton(self.tools)

        self.gridLayout_2.addWidget(self.btn_merge, 0, 0, 1, 2)
        self.drawind_zone.addWidget(self.tools)
        self.horizontalLayout.addLayout(self.drawind_zone)
        self.horizontalLayout.setStretch(1, 2)
        NewOrder.setCentralWidget(self.centralwidget)

        self.retranslateUi(NewOrder)
        self.add_connect()
        QtCore.QMetaObject.connectSlotsByName(NewOrder)

    def retranslateUi(self, NewOrder):
        _translate = QtCore.QCoreApplication.translate
        NewOrder.setWindowTitle(_translate("NewOrder", "Coupe"))
        self.btn_update.setText(_translate("NewOrder", "Сохранить"))
        self.btn_zero.setText(_translate("NewOrder", "Обнулить"))
        self.btn_quit.setText(_translate("NewOrder", "Выйти"))
        self.btn_frofiles.setText(_translate("NewOrder", "Профили"))
        self.btn_up_draw.setText(_translate("NewOrder", "Обн. чертеж"))
        self.ch_needsealer.setText(_translate("NewOrder", "Нужен уплотнитель?"))
        self.label_5.setText(_translate("NewOrder", "1"))
        self.size_1.setText(_translate("NewOrder", "..."))
        self.mat1.setItemText(0, _translate("NewOrder", "Стекло"))
        self.mat1.setItemText(1, _translate("NewOrder", "Зеркало"))
        self.mat1.setItemText(2, _translate("NewOrder", "ЛДСП"))
        self.label_6.setText(_translate("NewOrder", "2"))
        self.size_2.setText(_translate("NewOrder", "..."))
        self.mat2.setItemText(0, _translate("NewOrder", "Стекло"))
        self.mat2.setItemText(1, _translate("NewOrder", "Зеркало"))
        self.mat2.setItemText(2, _translate("NewOrder", "ЛДСП"))
        self.label_7.setText(_translate("NewOrder", "3"))
        self.size_3.setText(_translate("NewOrder", "..."))
        self.mat3.setItemText(0, _translate("NewOrder", "Стекло"))
        self.mat3.setItemText(1, _translate("NewOrder", "Зеркало"))
        self.mat3.setItemText(2, _translate("NewOrder", "ЛДСП"))
        self.label_8.setText(_translate("NewOrder", "4"))
        self.size_4.setText(_translate("NewOrder", "..."))
        self.mat4.setItemText(0, _translate("NewOrder", "Стекло"))
        self.mat4.setItemText(1, _translate("NewOrder", "Зеркало"))
        self.mat4.setItemText(2, _translate("NewOrder", "ЛДСП"))
        self.label_9.setText(_translate("NewOrder", "5"))
        self.size5.setText(_translate("NewOrder", "..."))
        self.mat5.setItemText(0, _translate("NewOrder", "Стекло"))
        self.mat5.setItemText(1, _translate("NewOrder", "Зеркало"))
        self.mat5.setItemText(2, _translate("NewOrder", "ЛДСП"))
        self.label_10.setText(_translate("NewOrder", "6"))
        self.size_6.setText(_translate("NewOrder", "..."))
        self.mat6.setItemText(0, _translate("NewOrder", "Стекло"))
        self.mat6.setItemText(1, _translate("NewOrder", "Зеркало"))
        self.mat6.setItemText(2, _translate("NewOrder", "ЛДСП"))
        self.label_11.setText(_translate("NewOrder", "7"))
        self.size_7.setText(_translate("NewOrder", "..."))
        self.mat7.setItemText(0, _translate("NewOrder", "Стекло"))
        self.mat7.setItemText(1, _translate("NewOrder", "Зеркало"))
        self.mat7.setItemText(2, _translate("NewOrder", "ЛДСП"))
        self.glass_w.setText(_translate("NewOrder", "Ширина  стекла"))
        self.mirror_w.setText(_translate("NewOrder", "Ширина зеркала"))
        self.LDSP_w.setText(_translate("NewOrder", "Ширина ЛДСП"))
        self.overlay_long.setText(_translate("NewOrder", "Длинна"))
        self.overlay_count.setText(_translate("NewOrder", "Количество"))
        self.r_no_overlay.setText(_translate("NewOrder", "Нет\n"
"накладки"))
        self.r_have_overlay.setText(_translate("NewOrder", "Есть накладка\n"
"для направ."))
        self.r_have_schlegel.setText(_translate("NewOrder", "Считать шлегель"))
        self.r_no_schlegel.setText(_translate("NewOrder", "Шлегель не нужен"))
        self.r_2_guide.setText(_translate("NewOrder", "2-х полозн. напрявляющая"))
        self.r_1_guide.setText(_translate("NewOrder", "1 полозн. напрявляющая"))
        self.r_black_char.setText(_translate("NewOrder", "Черные надписи на чертеже"))
        self.r_white_char.setText(_translate("NewOrder", "Белые надписи на чертеже"))
        self.r_no_fraction.setText(_translate("NewOrder", "Отбрасывать дробную часть"))
        self.r_show_fraction.setText(_translate("NewOrder", "Показывать дробную часть"))
        self.r_no_pack.setText(_translate("NewOrder", "Без упаковки (умолчание)"))
        self.r_packin_tape.setText(_translate("NewOrder", "В пленку"))
        self.r_packin_corrugation.setText(_translate("NewOrder", "В гофру"))
        self.r_packin_box.setText(_translate("NewOrder", "В ящик"))
        self.r_mechanismR.setText(_translate("NewOrder", "Механизм R+ (без направл.)"))
        self.r_mechanismUFK.setText(_translate("NewOrder", "Механизм ЮФК (с напрввл.)"))
        self.r_build.setText(_translate("NewOrder", "Сборка (умолчание)"))
        self.r_cut.setText(_translate("NewOrder", "Нарезка"))
        self.r_cutandrill.setText(_translate("NewOrder", "Нарезка, сверловка"))
        self.date.setText(_translate("NewOrder", "Дата"))
        self.norder.setText(_translate("NewOrder", "№ Заказа"))
        self.dateout.setText(_translate("NewOrder", "Дата выдачи"))
        self.discription.setText(_translate("NewOrder", "Описание"))
        self.color.setText(_translate("NewOrder", "Цвет"))
        self.profille.setText(_translate("NewOrder", "Профиль"))
        self.customer.setText(_translate("NewOrder", "Клиент"))
        self.btn_add_to_db.setText(_translate("NewOrder", "Внести"))
        self.door.setText(_translate("NewOrder", "Двери"))
        self.height.setText(_translate("NewOrder", "Высота"))
        self.long_2.setText(_translate("NewOrder", "Ширина"))
        self.longL2.setText(_translate("NewOrder", "Ширина L2"))
        self.r_nostandart_overlap.setText(_translate("NewOrder", "Нестандарт. перехлест"))
        self.r_no_overlap.setText(_translate("NewOrder", "Без перехлест."))
        self.inp_overlap_count.setText(_translate("NewOrder", "Количетво"))
        self.r_standart_overlap.setText(_translate("NewOrder", "Стандарт.  перехлест"))
        self.groupBox_11.setTitle(_translate("NewOrder", "Дополнительные материалы"))
        self.def_tape.setText(_translate("NewOrder", "Пленка защитная"))
        self.stop_up.setText(_translate("NewOrder", "Стопор для\n"
"верх. трека"))
        self.stop_down.setText(_translate("NewOrder", "Стопор для\n"
"нижн. трека"))
        self.posicioner.setText(_translate("NewOrder", "Позиционер"))
        self.plug.setText(_translate("NewOrder", "Загрушка"))
        self.pin_to_door.setText(_translate("NewOrder", "Саморез для\n"
"сборки дверей"))
        self.add_shlegel.setText(_translate("NewOrder", "Доб. шлегель"))
        self.add_sealer.setText(_translate("NewOrder", "Доб. уплотнитель"))
        self.groupBox_12.setTitle(_translate("NewOrder", "Доп. материалы для склад."))
        self.vertical_hand.setText(_translate("NewOrder", "Ручка вертикальная"))
        self.rolic_up.setText(_translate("NewOrder", "Ролик верхний петля"))
        self.plug_under_hand.setText(_translate("NewOrder", "Заглушка под ручку"))
        self.hand_fasteners.setText(_translate("NewOrder", "Крепеж для ручки"))
        self.def_tape_stok.setText(_translate("NewOrder", "Пленка защитная"))
        self.door_loop.setText(_translate("NewOrder", "Петля дверная"))
        self.loop_4.setText(_translate("NewOrder", "Петля 4-х шарнирная"))
        self.plug_stok.setText(_translate("NewOrder", "Заглушка"))
        self.pin_to_door_stok.setText(_translate("NewOrder", "Саморез для\n"
"сборки дверей"))
        self.r_no_dilivery.setText(_translate("NewOrder", "Без доставки"))
        self.radioButton_3r_dilivery.setText(_translate("NewOrder", "С доставкой"))
        self.verticalGroupBox.setTitle(_translate("NewOrder", "Чертеж"))
        self.btn_nimus.setText(_translate("NewOrder", "Масштаб -"))
        self.btn_grass.setText(_translate("NewOrder", "Стекло"))
        self.btn_mirror.setText(_translate("NewOrder", "Зеркало"))
        self.btn_LDSP.setText(_translate("NewOrder", "ЛДСП"))
        self.btn_plus.setText(_translate("NewOrder", "Масштаб +"))
        self.btn_unmerge.setText(_translate("NewOrder", "Разъеденить"))
        self.btn_merge.setText(_translate("NewOrder", "Объеденить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewOrder = QtWidgets.QMainWindow()
    ui = Ui_NewOrder()
    ui.setupUi(NewOrder)
    NewOrder.show()
    sys.exit(app.exec_())
