# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_profiles.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog, profiles):
        Dialog.setObjectName("Dialog")
        Dialog.resize(608, 487)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.tableWidget = QtWidgets.QTableView(Dialog)
        self.horizontalLayout.addWidget(self.tableWidget)

        self.tableWidget.set
        QtCore.QMetaObject.connectSlotsByName(Dialog)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog, (('открытый', 2, 2, 3), ('close', 0, 0, 4)))
    Dialog.show()
    sys.exit(app.exec_())
